server:
  port: 8990
  context-path: /zxpm
jsp-servlet:
  init-parameters:
    development: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: hr
    password: hr
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
    encoding:
      charset: utf-8
      force: true
mybatis:
  mapper-locations: com/baizhi/dao/*Mapper.xml
  type-aliases-package: com.baizhi.entity
